Repository halo-dev/plugin-app-store, pull requests merged in 2023-09, with the labels that each got.

#7 feat: refactor app-download hook to support binding
  console/postcss.config.js
  console/src/components/AppActionButton.vue
  console/src/components/AppCard.vue
  console/src/components/AppDetailModal.vue
  console/src/components/AppVersionCheckBar.vue
  console/src/components/ThemeOrPluginVersionCheckBar.vue
  console/src/components/detail/DetailReleaseItem.vue
  console/src/composables/use-app-download.ts
  console/src/constant/exception.ts
  console/src/constant/index.ts
  console/src/types/core.ts
Labels: kind/feature, lgtm, approved, release-note-none

#12 feat: add default border color for app card
  console/src/components/AppCard.vue
Labels: lgtm, approved, kind/improvement, release-note-none

#13 refactor: only query the necessary applications when checking updates
  console/package.json
  console/pnpm-lock.yaml
  console/src/composables/use-app-compare.ts
  console/src/composables/use-app-download.ts
  console/src/composables/use-plugin-version.ts
  console/src/composables/use-plugin.ts
  console/src/composables/use-theme-version.ts
  console/src/composables/use-theme.ts
  console/src/utils/store-api-client.ts
Labels: release-note, lgtm, approved, kind/improvement

#15 fix: the download is empty when downloads is undefined
  console/src/components/detail/DetailSidebar.vue
Labels: release-note, lgtm, approved

#14 feat: add supports for only query installed apps in app store page
  console/src/views/AppStore.vue
Labels: kind/feature, release-note, lgtm, approved

#18 fix: border radius style issue of app card
  console/src/components/AppCard.vue
Labels: kind/bug, release-note, lgtm, approved

#19 fix: can not display title of readme screenshots
  console/src/components/AppCard.vue
  console/src/components/AppStoreTab.vue
  console/src/components/detail/DetailReadme.vue
  console/src/views/AppStore.vue
Labels: kind/bug, release-note, lgtm, approved

#20 feat: make app card more round
  console/src/components/AppCard.vue
Labels: release-note, lgtm, approved, kind/improvement

#24 refactor: change app store default view to grid
  console/src/views/AppStore.vue
Labels: lgtm, approved, kind/improvement, release-note-none

#23 feat: add plugin and theme binding check field
  console/src/components/entity-fields/PluginBindingCheckField.vue
  console/src/components/operation-items/ThemeBindingCheckOperationItem.vue
  console/src/index.ts
Labels: release-note, lgtm, approved, kind/improvement

#25 feat: add data tracker for app detail modal
  console/.eslintrc.cjs
  console/env.d.ts
  console/package.json
  console/pnpm-lock.yaml
  console/src/components/AgreementsModal.vue
  console/src/components/AppDetailModal.vue
  console/src/components/AppStoreTab.vue
  console/src/composables/use-configmap.ts
  console/src/constant/index.ts
  console/src/index.ts
  console/src/types/index.ts
  console/src/views/AppStore.vue
  console/src/views/PrivacyPolicy.md
  console/src/views/PrivacyPolicy.vue
  console/tailwind.config.js
  console/vite.config.ts
  src/main/resources/extensions/settings.yaml
  src/main/resources/plugin.yaml
Labels: kind/feature, release-note, lgtm, approved

#26 refactor: remove comment tab panel in app detail modal
  console/src/components/AppDetailModal.vue
Labels: release-note, lgtm, approved, kind/improvement

#28 Add appstore management role template
  src/main/resources/extensions/store-role-template.yaml
Labels: lgtm, approved, release-note-none

#30 chore: update app store backend server address
  console/.env
  console/src/components/AgreementsModal.vue
  console/src/components/AppActionButton.vue
  console/src/components/AppDetailModal.vue
  src/main/resources/extensions/settings.yaml
Labels: lgtm, approved, kind/improvement, release-note-none

#29 feat: refine ui permissions check
  console/src/index.ts
  src/main/resources/extensions/store-role-template.yaml
Labels: kind/feature, release-note, lgtm, approved

#27 feat: add supports for setting pat to bind with halo app store
  console/src/components/plugin-tabs/AccountBindingTab.vue
  console/src/constant/index.ts
  console/src/index.ts
  console/src/utils/api-client.ts
  console/src/utils/store-api-client.ts
Labels: kind/feature, release-note, lgtm, approved

#31 feat: add supports for downloading and updating paid apps
  console/package.json
  console/pnpm-lock.yaml
  console/src/components/AppActionButton.vue
  console/src/components/AppCard.vue
  console/src/components/AppDetailModal.vue
  console/src/components/AppVersionCheckBar.vue
  console/src/components/PaymentCheckModal.vue
  console/src/components/ThemeOrPluginVersionCheckBar.vue
  console/src/components/detail/DetailReleaseItem.vue
  console/src/composables/use-app-download.ts
  console/src/composables/use-payment-check-modal.ts
  console/src/types/index.ts
  console/vite.config.ts
Labels: kind/feature, release-note, lgtm, approved

#35 fix: can not refetch when request parameters changed
  console/src/components/AgreementsModal.vue
  console/src/components/AppStoreTab.vue
Labels: kind/bug, release-note, lgtm, approved

#34 feat: open app detail modal by click app cover
  console/src/components/AppCard.vue
Labels: lgtm, approved, kind/improvement, release-note-none

#37 refactor: update halo pat management page address
  console/src/components/plugin-tabs/AccountBindingTab.vue
Labels: lgtm, approved, release-note-none

#36 feat: store query params to location href in app store page
  console/package.json
  console/pnpm-lock.yaml
  console/src/views/AppStore.vue
Labels: kind/feature, release-note, lgtm, approved

#40 chore: add check step for github action
  .github/workflows/workflow.yaml
  console/.eslintrc.cjs
  console/env.d.ts
  console/package.json
  console/pnpm-lock.yaml
  console/src/components/AppActionButton.vue
  console/src/components/operation-items/ViewAppStoreOperationItem.vue
  console/src/composables/use-app-compare.ts
  console/src/utils/__tests__/date.spec.ts
Labels: lgtm, approved, kind/improvement, release-note-none

#39 refactor: app version requires check
  console/src/components/detail/DetailReleaseItem.vue
  console/src/composables/use-app-compare.ts
  console/src/composables/use-plugin-version.ts
  console/src/composables/use-theme-version.ts
  console/src/utils/__tests__/version.spec.ts
  console/src/utils/version.ts
Labels: release-note, lgtm, approved, kind/improvement
